### ISSUE TITLE
Question about the number of parameters

### ISSUE THREAD

**Issue by bokyeong1015** [CASIA-IVA-Lab/FLAP#2]
Hi, thank you for sharing your impressive work.

I think there might be a need to modify the below line [[link](https://github.com/CASIA-IVA-Lab/FLAP/blob/6b0fc0003824d349ee061487e25ee2054fc03186/main.py#L92)].
`print(f"model parameter {sum(p.numel() for p in model.parameters()) / 1024 ** 3:.2f}B")`

Instead of dividing the number of parameters by `1024 ** 3` to calculate the parameters in billions, it might be more accurate to use `1000 ** 3`. Specifically, when I checked the number of parameters of the following models, the results are:

- LLaMA-7B: 6738415616 = 6.74B
- LLM-Pruner’s code (20% pruning) [[link](https://github.com/horseee/LLM-Pruner/tree/213ffa4d02f92f16d29219a97fd01a8622db1550?tab=readme-ov-file#1-pruning-discovery-stage--estimation-stage)]: 5422977024 = 5.42B
- FLAP’s code (20% pruning) [[link](https://github.com/CASIA-IVA-Lab/FLAP/tree/6b0fc0003824d349ee061487e25ee2054fc03186?tab=readme-ov-file#pruning)]: 5442514944 = 5.44B (not 5.07B)

I would appreciate it if you could share your opinion. Thank you for your time and consideration.

**Comment by an-yongqi** [comment]
@bokyeong1015 Thanks for attention. You are correct. Due to an oversight in my coding, there was an error in our calculation method. I have now updated the code to address this issue.
