### ISSUE TITLE
Question about the wikitext2 data loader

### ISSUE THREAD

**Issue by bokyeong1015** [CASIA-IVA-Lab/FLAP#3]
Thanks for your nice work. When running the sample script, I'm getting the following error message regarding the wikitext2 loader. Would you kindly check it?

```
File "/ssd2/bkkim/FLAP/lib/data.py", line 81, in get_wikitext2
    traindata = load_dataset('text', data_files='datasets/wikitext/wiki.train.raw', split="train")
FileNotFoundError: Unable to find '/ssd2/bkkim/FLAP/datasets/wikitext/wiki.train.raw'
```

By the way, I found a workaround for the issue by using the comment lines in [the script](https://github.com/CASIA-IVA-Lab/FLAP/blob/6b0fc0003824d349ee061487e25ee2054fc03186/lib/data.py#L78-L82). Is this an appropriate solution?

```python
# traindata = load_dataset('wikitext', 'wikitext-2-raw-v1', split='train')
# testdata = load_dataset('wikitext', 'wikitext-2-raw-v1', split='test')
```

Thank you for your time.

**Comment by an-yongqi** [comment]
@bokyeong1015  Due to my server's inability to directly access HuggingFace for downloading datasets, I opted for local loading during my experimentation. You can replace it with the two lines of code commented in the script, which should resolve this issue.
