### ISSUE TITLE
 how much data was used in the pruning process?

### ISSUE THREAD

**Issue by wyxscir** [CASIA-IVA-Lab/FLAP#4]
I would like to know how much data was used in the pruning process? Is it just like the example code where nsample=1024, indicating that only 1024 data were used to determine the pruning results?

**Comment by an-yongqi** [comment]
Yes, you are correct. In our pruning process, the default number of samples (nsamples) is set to 1024, as specified in the scripts/llama_7b.sh script. This is consistent across other scripts as well, where nsamples is set to 1024. The results presented in our paper are based on using nsamples=1024 for the pruning analysis. This number was chosen to balance between computational efficiency and the representativeness of the sample for determining effective pruning outcomes. If you have any further questions or need clarification on other aspects of our work, please do not hesitate to reach out.

**Comment by wyxscir** [comment]
Thanks for your reply, I understand
